baseURL = 'https://dev-undergrad.dev/'
languageCode = 'en-us'
title = 'undergrad work'
theme = 'shibui'

[menu]
    [[menu.main]]
        name = "notes"
        url  = "/notes/" 
        weight = 1 
    [[menu.main]] 
        name = "resume" 
        url  = "/resume.pdf"
        weight = 2 
    [[menu.main]] 
        name = "if your name is Annika" 
        url  = "/valentine/index.html"




